FROM python:3.10-slim as builder

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./worker/requirements.txt .
COPY .env .

RUN pip install -r requirements.txt

COPY ./worker/ ./worker/
COPY ./db/ ./db/

# final stage
FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
COPY --from=builder /app/ .

ENV PATH="/opt/venv/bin:$PATH"

# RUN cd db && alembic upgrade head

# CMD ["python3", "/app/worker/etl.py"]