CREATE TYPE category AS ENUM ('Eletronics', 'Clothing', 'Food');
CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    QUANTITY INTEGER NOT NULL,
    CATEGORY category 
);